### ISSUE TITLE
When changing Ability score generation, the field under it does not change until foundry is restarted.

### ISSUE THREAD

**Issue by mohd2126** [Sayshal/hero-mancer#1] opened 2024-10-27 06:50 UTC
https://github.com/user-attachments/assets/92da7746-a612-4e1f-8a92-e6410040fb3a

**Comment by Sayshal** [comment] 2024-10-28 17:57
I will add hint text the specifies a reload is required. To my knowledge foundry doesn't support inline refreshing of content with a reload. The expected behavior is a reload after changing the settings regardless due to the logic needing updating for what is displayed in the application.

**Comment by mohd2126** [comment] 2024-10-28 21:31
Without an indication, I'd assume some people wouldn't know the option exists as they wouldn't reopen the settings to check after they refresh.

**Comment by Sayshal** [comment] 2024-10-29 01:29
> Without an indication, I'd assume some people wouldn't know the option exists as they wouldn't reopen the settings to check after they refresh.

Fixed in [0.2.0](https://github.com/Sayshal/hero-mancer/releases/tag/0.2.0)

**Closed by Sayshal** 2024-10-29 01:29 UTC
Labels: documentation
