### ISSUE TITLE
Ability Scores not named while manual rolling

### ISSUE THREAD

**Issue by mohd2126** [Sayshal/hero-mancer#2] opened 2024-10-27 06:57 UTC
![image](https://github.com/user-attachments/assets/e52af2f5-793a-4ce4-89e9-98f4a5bc1c3a)

Also, I suggest having separate fields for rolling and inputting the scores, so one doesn't have to stick the roll to the same ability score it's rolled at; the way you implemented standard array, just make it replace the scores from standard array with what's rolled.

**Comment by mohd2126** [comment] 2024-10-27 06:59
Another suggestion: add the ability for custon ASIs afterwards.

**Comment by Sayshal** [comment] 2024-10-28 17:55
@mohd2126 can you expand further on your comment(s)?

The current workflow with manual rolling enabled is to allow the player to roll and then using the dropdown in the screenshot above, decide after rolling what stat to assign to the roll. Do you expect it in a different format?

**Comment by mohd2126** [comment] 2024-10-28 21:21
> > Another suggestion: add the ability for custom ASIs afterwards.
> 
> Do you mean custom ASI's as GM-inputted via a setting, or pulling from the character class/race/background?

Why not both if possible?

**Comment by mohd2126** [comment] 2024-10-28 21:37
Maybe also add an option for the gm to offer a level 1 feat, since it's an extremely common house rule.

**Comment by Sayshal** [comment] 2024-10-29 01:21
> > @mohd2126 can you expand further on your comment(s)?
> > The current workflow with manual rolling enabled is to allow the player to roll and then using the dropdown in the screenshot above, decide after rolling what stat to assign to the roll. Do you expect it in a different format?
> 
> That is exactly how I expected it to work, but it doens't seem to, so I thought my expectations were wrong. ![image](https://private-user-images.githubusercontent.com/41587665/380896883-c18f23e1-f1a5-4922-8d1c-dd07665cb3bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjQ5NjcsIm5iZiI6MTczMDE2NDY2NywicGF0aCI6Ii80MTU4NzY2NS8zODA4OTY4ODMtYzE4ZjIzZTEtZjFhNS00OTIyLThkMWMtZGQwNzY2NWNiM2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDAxMTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjJkMjA1M2I5ODczMTE0NjUzNjJjNTVmZDU2MDg4ZDJjNzE0ODNhZGY0ZGFmZGIzODlmODllM2Q0ZTI3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EA1_dDRuYErv01ASA9zV33UL_oW7Kfy4FzjzXr5nBUg) The only available choice after rolling is "choose"

This was a bug! Please test again in 0.2.0.



> > > Another suggestion: add the ability for custom ASIs afterwards.
> > 
> > 
> > Do you mean custom ASI's as GM-inputted via a setting, or pulling from the character class/race/background?
> 
> Why not both if possible?
> 
> But I was specifically talking about the former.

The class/background stuff is done post-submission (or will be once advancements work as intended.) As for custom ASI increases, what would you want it to look like?


> Maybe also add an option for the gm to offer a level 1 feat, since it's an extremely common house rule.

I'll add this as a seperate feature request to be added to the background tab if enabled by the DM. Shouldn't be too difficult.

**Comment by mohd2126** [comment] 2024-10-29 07:01
>This was a bug! Please test again in 0.2.0.
Still the same problem I'm afriad.
![image](https://github.com/user-attachments/assets/b2981933-dc24-4678-8904-e546a4cac091)

**Comment by mohd2126** [comment] 2024-10-29 07:13
lol, I found another [issue](https://github.com/Sayshal/hero-mancer/issues/4) while testing this one

**Comment by mohd2126** [comment] 2024-10-29 07:27
>As for custom ASI increases, what would you want it to look like?

Maybe something like this
![image](https://github.com/user-attachments/assets/fd4a7ede-6243-47f9-bbf0-fd656c3847b2)
## Or this
![image](https://github.com/user-attachments/assets/49a95bd9-8b38-4749-a3fd-9846b39fe5e8)

**Comment by Sayshal** [comment] 2024-10-30 06:13
> > As for custom ASI increases, what would you want it to look like?
> 
> Maybe something like this ![image](https://private-user-images.githubusercontent.com/41587665/381021473-fd4a7ede-6243-47f9-bbf0-fd656c3847b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjkwNTAsIm5iZiI6MTczMDI2ODc1MCwicGF0aCI6Ii80MTU4NzY2NS8zODEwMjE0NzMtZmQ0YTdlZGUtNjI0My00N2Y5LWJiZjAtZmQ2NTZjMzg0N2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA2MTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDIzYjRhNGUxMzg3NGMwY2QwNGRjNzg2MDBlNTljZTgwYTdjMWFmN2YxNzc0ZmQ3Mjk4OGQ5YTMzZjkzZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fsi6c5ODhzdXCgPXXRWlT-jz007ozHlaNHcYZkWL54o)
> 
> ## Or this
> ![image](https://private-user-images.githubusercontent.com/41587665/381022015-49a95bd9-8b38-4749-a3fd-9846b39fe5e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjkwNTAsIm5iZiI6MTczMDI2ODc1MCwicGF0aCI6Ii80MTU4NzY2NS8zODEwMjIwMTUtNDlhOTViZDktOGIzOC00NzQ5LWEzZmQtOTg0NmIzOWZlNWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA2MTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZTJhNWI3MjgxYTMwOWNjMjEwZThhY2YwOGVlZGM0NzkzNmY3ZmFjYWJlNzI1ZjgyYjJlMjg2NGY2ZjEyOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BP8dctZ8ddYZmRflLOAUioes-YEApLcFrsvHYmhHK94)

I'm going to pass for now on this feature request. I will likely add a roll all dice button but as for the custom ASI, that is to be covered during the sheet creation/built-in advancement system - I don't want to do the work twice. Feel free to make a feature request for tracking and we'll go from there.

**Comment by Sayshal** [comment] 2024-10-30 06:14
Closed.

**Closed by Sayshal** 2024-10-30 06:13 UTC
Labels: question

**Comment by mohd2126** [comment] 2024-10-30 07:26
@Sayshal was the main issue fixed? The ability scores not being named and the choose selection being broken.

**Comment by Sayshal** [comment] 2024-10-30 09:08
> @Sayshal was the main issue fixed? The ability scores not being named and the choose selection being broken.
I believe this should all be fixed now in 0.2.2. The ability scores I assigned via a dropdown and you can roll, this way you can re-assign easily rather than having to manually change the value if you decide to change what's assigned. The expected workflow is you roll all the dice first and then assign values. To that effect, I've added a stretch goal to move the dice rolling to the top instead of underneath and will play with that once the application is fully released.

**Comment by mohd2126** [comment] 2024-10-30 10:15
Seems to work.
